Create an array/tensor from a list

In [3]:
import numpy
from fastai.vision.all import *

In [5]:
data =[[1,2,3],[4,5,6]]
arr = array(data)
tns = tensor(data)

In [6]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
tns

tensor([[1, 2, 3],
        [4, 5, 6]])

Select a row

In [8]:
tns[1]

tensor([4, 5, 6])

Select a column. `:` indicates all of the first axis/dimension

In [41]:
tns[: , 1]

tensor([2, 5])

Select part of a row or column. the end 3 is excluded.

In [47]:
tns[1,1:3]

tensor([5, 6])

Operators on tensors. 

In [48]:
tns,tns+1

(tensor([[1, 2, 3],
         [4, 5, 6]]),
 tensor([[2, 3, 4],
         [5, 6, 7]]))

In [50]:
tns.type()

'torch.LongTensor'

In [54]:
# automatically changes type to float
(tns*1.5).type()

'torch.FloatTensor'